In [44]:
sent=['the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',]

In [45]:
from tensorflow.keras.preprocessing.text import one_hot
import numpy as np

In [46]:
# one hot representation

In [47]:
voc_size =1000

onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[180, 625, 916, 731], [180, 533, 916, 66], [439, 757, 132, 767, 252], [439, 757, 132, 767, 944]]


In [48]:
# word embedding

In [49]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [50]:
sent_length=5
embedded_docs=pad_sequences(onehot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)


[[180 625 916 731   0]
 [180 533 916  66   0]
 [439 757 132 767 252]
 [439 757 132 767 944]]


In [51]:
dim=10

model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 5, 10)             10000     
Total params: 10,000
Trainable params: 10,000
Non-trainable params: 0
_________________________________________________________________


In [52]:
print(model.predict(embedded_docs))

[[[-0.01077331 -0.00324965  0.02055401 -0.00193576  0.01556397
   -0.0243077  -0.03791272 -0.00810267  0.03629733  0.03812115]
  [ 0.00648445  0.04330229 -0.00434984 -0.02909525 -0.030327
    0.03126245 -0.04702377 -0.01369915  0.03625511 -0.01510476]
  [-0.04111216 -0.03116969  0.04439737 -0.00473296 -0.01989591
    0.00710883  0.02474073 -0.03598054  0.00557012  0.0385558 ]
  [ 0.00140917  0.0459047  -0.02070429  0.04429081 -0.02683876
    0.02062919 -0.03549608  0.02366589 -0.01745067 -0.0294189 ]
  [ 0.01836905  0.04299786 -0.01415057 -0.00362287 -0.02782579
   -0.01300379  0.0033929  -0.00635369  0.00050105  0.04394839]]

 [[-0.01077331 -0.00324965  0.02055401 -0.00193576  0.01556397
   -0.0243077  -0.03791272 -0.00810267  0.03629733  0.03812115]
  [ 0.029575    0.04716751 -0.0437423   0.03384656  0.04003558
   -0.00462423  0.00583358  0.00513978 -0.04200792  0.02168466]
  [-0.04111216 -0.03116969  0.04439737 -0.00473296 -0.01989591
    0.00710883  0.02474073 -0.03598054  0.005570

In [53]:
embedded_docs[0]

array([180, 625, 916, 731,   0])

In [54]:
print(model.predict(embedded_docs)[0])

[[-0.01077331 -0.00324965  0.02055401 -0.00193576  0.01556397 -0.0243077
  -0.03791272 -0.00810267  0.03629733  0.03812115]
 [ 0.00648445  0.04330229 -0.00434984 -0.02909525 -0.030327    0.03126245
  -0.04702377 -0.01369915  0.03625511 -0.01510476]
 [-0.04111216 -0.03116969  0.04439737 -0.00473296 -0.01989591  0.00710883
   0.02474073 -0.03598054  0.00557012  0.0385558 ]
 [ 0.00140917  0.0459047  -0.02070429  0.04429081 -0.02683876  0.02062919
  -0.03549608  0.02366589 -0.01745067 -0.0294189 ]
 [ 0.01836905  0.04299786 -0.01415057 -0.00362287 -0.02782579 -0.01300379
   0.0033929  -0.00635369  0.00050105  0.04394839]]
